### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TheDiego845** [MrTigreroux/TigerReportsSupports#10]
java.lang.IllegalArgumentException: URL must be a valid http(s) or attachment url.
        at net.dv8tion.jda.internal.utils.Checks.check(Checks.java:43) ~[TigerReportsSupports.jar:?]
        at net.dv8tion.jda.api.EmbedBuilder.urlCheck(EmbedBuilder.java:838) ~[TigerReportsSupports.jar:?]
        at net.dv8tion.jda.api.EmbedBuilder.setThumbnail(EmbedBuilder.java:506) ~[TigerReportsSupports.jar:?]
        at fr.mrtigreroux.tigerreportssupports.bots.DiscordBot.notifyReport(DiscordBot.java:187) ~[TigerReportsSupports.jar:?]
        at fr.mrtigreroux.tigerreportssupports.listeners.ReportListener.onNewReport(ReportListener.java:35) ~[TigerReportsSupports.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor365.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-255]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-255]
        at fr.mrtigreroux.tigerreports.utils.ReportUtils.sendReport(ReportUtils.java:56) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.commands.ReportCommand.finalReportCommandProcess(ReportCommand.java:296) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.commands.ReportCommand.access$200(ReportCommand.java:36) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.commands.ReportCommand$2$2$1$1.run(ReportCommand.java:263) ~[TigerReports.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-255]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by MrTigreroux** [comment]
What have you configured for Config: Discord: Thumbnail setting in config.yml file of TigerReportsSupports plugin ?
