### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by masterhacka** [MrTigreroux/TigerReportsSupports#21]
[22:31:03 ERROR]: Error occurred while enabling TigerReportsSupports v1.6.3 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:275) ~[TigerReportsSupports.jar:?]
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:248) ~[TigerReportsSupports.jar:?]
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1931) ~[TigerReportsSupports.jar:?]
        at fr.mrtigreroux.tigerreportssupports.bots.DiscordBot.connect(DiscordBot.java:49) ~[TigerReportsSupports.jar:?]
        at fr.mrtigreroux.tigerreportssupports.TigerReportsSupports.onEnable(TigerReportsSupports.java:75) ~[TigerReportsSupports.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.mcnative.runtime.bukkit.plugin.McNativePluginWrapperLoader.enablePlugin(McNativePluginWrapperLoader.java:138) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
        at net.pretronic.libraries.logging.bridge.slf4j.SLF4JBridgeServiceProvider.getMDCAdapter(SLF4JBridgeServiceProvider.java:69) ~[?:?]
        at org.slf4j.MDC.<clinit>(MDC.java:91) ~[slf4j-api-1.8.0-beta4.jar:1.8.0-beta4]
        ... 17 more

**Comment by MrTigreroux** [comment]
I tested and did not have any issue. I think that you miss configured your Discord bot token.
In any case, I updated the JDA API to last stable version in the new [1.6.4 version](https://www.spigotmc.org/resources/tigerreportssupports.54612/update?update=444211).
Try with that new version and let me know if you still have problem.

**Comment by masterhacka** [comment]
Unfortunately it didn't change a thing. I am using pterodactyl. After changing Java Version it didn't work.

**Comment by MrTigreroux** [comment]
Is it the same error ? Can you give me all the log file (from start to end) hiding sensitive information please ?

**Comment by masterhacka** [comment]
I have several servers on my bungee network. All TigerReports configs are the same.
On one server it seems to work: https://pastebin.com/yicf9MM7
On some not: https://pastebin.com/sdDr8TaP

**Comment by MrTigreroux** [comment]
Ok thank you, could you try to use the same plugins where TigerReportsSupports works in the server where TigerReportsSupports doesn't work (removing BentoBox, LeaderHeadsRevamped, McNative and WorldBorderAPI in the server where TigerReportsSupports doesn't work), then give me the logs again of that server with the list of plugins as you did in your pastebins at the end.

**Comment by masterhacka** [comment]
McNative comes from CitybuildV2 but here it is: https://pastebin.com/i4jmuiMr
It seems to work

**Comment by MrTigreroux** [comment]
Really interesting, the problem comes when you have one or more of the plugins: BentoBox, CityBuildV2, LeaderHeadsRevamped, McNative, WorldBorderAPI.
If you could try to put back, one by one, those plugins and check when the error occurs in order to find what plugin is causing problem.

**Comment by masterhacka** [comment]
CityBuildV2 is causing the problem

**Comment by MrTigreroux** [comment]
Could you try to remove CityBuildV2 and keep McNative and tell me if you still have an error or not please ?

**Comment by masterhacka** [comment]
McNative is included in CityBuild and not a standalone plugin. So I can’t remove it seperately

**Comment by MrTigreroux** [comment]
Ok, I think the problem comes from McNative. The way CityBuildV2 is distributed is really curious. To explain it simply: the file that you download from the SpigotMC page to get CityBuildV2 plugin is just a plugin which runs McNative and asks it to download from the internet the plugin CityBuildV2. Concretly, I can't see the source code of the plugin because I would need to install an 1.16.4 or more Spigot which I don't have for now and run the downloaded file in order for it to download the real plugin code...
So if you can give me your CityBuildV2.jar file that will save me time.

**Comment by masterhacka** [comment]
Thank you so much for your help. Hopefully one of this is correct for your needs:
[CityBuild.zip](https://github.com/MrTigreroux/TigerReportsSupports/files/8036152/CityBuild.zip)

**Comment by MrTigreroux** [comment]
Thank you. That allowed me to spot the issue.
Here it is: https://github.com/Pretronic/PretronicLibraries/blob/86faf72f2b571224122b6cbadcefdd4b3b898148/pretroniclibraries-logging/src/main/java/net/pretronic/libraries/logging/bridge/slf4j/SLF4JBridgeServiceProvider.java#L69

This line of code is the error you get:
"Caused by: java.lang.UnsupportedOperationException
	at net.pretronic.libraries.logging.bridge.slf4j.SLF4JBridgeServiceProvider.getMDCAdapter(SLF4JBridgeServiceProvider.java:69) ~[?:?]"

Concretly, CityBuildV2 (or McNative) uses PretronicLibraries which modifies the SLF4JServiceProvider with one which doesn't support MDC. To be honest, I don't know what this SLF4JServiceProvider is and why PretronicLibraries uses a custom one. All I can understand is that their custom SLF4JServiceProvider is used for your whole server and TigerReportsSupports uses the JDA API which uses SLF4J for logging. The standard SLF4J works great, but CityBuildV2 doesn't use a standard SLF4J.
To conclude, the problem doesn't seem to come from TigerReportsSupports but from PretronicLibraries, used by CityBuildV2.

**Comment by masterhacka** [comment]
Thank you very much! I will contact the CityBuild dev and hopefully it get fixed soon.

**Comment by MrTigreroux** [comment]
But in your situation, a quick fix is to install TigerReportsSupports in only one Spigot server, a Spigot server where you don't have CityBuildV2.
